# Generated by Django 5.2.5 on 2025-08-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PASSWORD_CHANGE', 'Password Changed'), ('CUSTOMER_CREATED', 'Customer Created'), ('CUSTOMER_UPDATED', 'Customer Updated'), ('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('QUOTATION_CREATED', 'Quotation Created'), ('QUOTATION_UPDATED', 'Quotation Updated'), ('QUOTATION_STATUS_CHANGED', 'Quotation Status Changed'), ('QUOTATION_SENT', 'Quotation Sent'), ('QUOTATION_VIEWED', 'Quotation Viewed by Customer'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('SYSTEM_NOTIFICATION', 'System Notification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold')], default='PENDING', max_length=20),
        ),
    ]
