# Generated by Django 5.2.5 on 2025-08-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='terms',
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms',
            field=models.ManyToManyField(blank=True, to='quotations.termsandconditions'),
        ),
    ]
