# Generated by Django 5.2.5 on 2025-08-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_alter_quotation_status_remove_quotation_terms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='drive_web_view_link',
            new_name='file_url',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='drive_file_id',
        ),
    ]
