# Generated by Django 5.2.5 on 2025-08-25 05:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_rename_drive_web_view_link_quotation_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
    ]
