# Generated by Django 5.2.5 on 2025-08-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_quotation_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
