# Generated by Django 5.2.5 on 2025-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('meter', 'Meter')], default='piece', max_length=10, null=True),
        ),
    ]
