# Generated by Django 5.2.5 on 2025-08-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_alter_product_active_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='quotations.product'),
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
