# Generated by Django 5.2.5 on 2025-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
