# Generated by Django 5.2.5 on 2025-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='product',
            field=models.ManyToManyField(blank=True, to='quotations.product'),
        ),
    ]
