# Generated by Django 5.2.5 on 2025-08-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_alter_quotation_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
