# Generated by Django 5.2.5 on 2025-08-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold'), ('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent')], default='PENDING', max_length=20),
        ),
    ]
