# Generated by Django 5.2.5 on 2025-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Social Media'), ('EMAIL', 'Email Campaign'), ('COLD_CALL', 'Cold Call'), ('EXHIBITION', 'Exhibition/Trade Show'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20),
        ),
    ]
