# Generated by Django 5.2.5 on 2025-08-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_remove_lead_source_lead_lead_source_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='quotation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='has_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
