# Generated by Django 5.2.5 on 2025-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_lead_quotation_id_quotation_has_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('number', 'Number')], default='percentage', max_length=20, null=True),
        ),
    ]
