# Generated by Django 5.2.5 on 2025-08-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_quotation_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('amount', 'Amount')], default='percentage', max_length=20, null=True),
        ),
    ]
