# Generated by Django 5.2.5 on 2025-09-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0025_remove_quotation_product_productdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='tax_total',
            new_name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profit_margin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='tax_rate',
        ),
    ]
