# Generated by Django 5.2.5 on 2025-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0026_rename_tax_total_quotation_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
