# Generated by Django 5.2.5 on 2025-09-05 19:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0030_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
