# Generated by Django 5.2.5 on 2025-09-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0031_alter_productdetails_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='quotations.customer'),
        ),
    ]
