# Generated by Django 5.2.5 on 2025-09-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0032_activitylog_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additionalNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
