# Generated by Django 5.2.5 on 2025-10-16 19:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0035_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='additional_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='additional_charge_name',
            field=models.CharField(blank=True, default='Additional Charges', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SalespersonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'SALESPERSON'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salesperson Permission',
                'verbose_name_plural': 'Salesperson Permissions',
            },
        ),
    ]
