# Generated by Django 5.2.5 on 2025-10-20 05:31

import apps.quotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0036_quotation_additional_charge_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespersonpermission',
            name='permissions',
            field=models.JSONField(blank=True, default=apps.quotations.models.get_default_permissions),
        ),
    ]
