# Generated by Django 5.2.5 on 2025-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0039_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
