# Generated by Django 5.2.5 on 2025-11-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0041_leaddescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddescription',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
