# Generated by Django 5.2.5 on 2025-11-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0042_alter_leaddescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('QUOTATION', 'Quotation'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('SOCIAL_MEDIA', 'Social Media'), ('EMAIL', 'Email Campaign'), ('COLD_CALL', 'Cold Call'), ('EXHIBITION', 'Exhibition/Trade Show'), ('EXISTING_CUSTOMER', 'Existing Customer'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
