# Generated by Django 5.2.5 on 2025-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0044_alter_lead_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVISED', 'Revised')], default='DRAFT', max_length=20),
        ),
    ]
