# Generated by Django 5.2.5 on 2025-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0047_alter_signatureimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold'), ('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('PRIORITY', 'Priority'), ('REVISED', 'Revised'), ('PROSPECTIVE', 'Prospective')], default='PROSPECTIVE', max_length=20),
        ),
    ]
