# Generated by Django 5.2.5 on 2025-12-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0048_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('ON_HOLD', 'On Hold'), ('NEW', 'New'), ('QUALIFIED', 'Qualified'), ('PROPOSAL', 'Proposal Sent'), ('PRIORITY', 'Priority'), ('REVISED', 'Revised'), ('PROSPECTIVE', 'Prospective'), ('NEGOTIATION', 'Negotiation')], default='PROSPECTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVISED', 'Revised'), ('NEGOTIATION', 'Negotiation')], default='DRAFT', max_length=20),
        ),
    ]
