# Generated by Django 5.2.5 on 2026-01-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0049_alter_lead_status_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
