# Generated by Django 5.2.5 on 2026-01-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0050_lead_lead_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
