# Generated by Django 5.2.5 on 2026-01-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0051_alter_lead_lead_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
    ]
