# Generated by Django 5.2.5 on 2026-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0053_alter_lead_lead_number'),
    ]

    operations = []

