# Generated by Django 5.2.5 on 2026-01-31 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0054_remove_lead_quotation_id_lead_quotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationLeadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_links', to='quotations.lead')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_links', to='quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
