# Generated by Django 5.2.5 on 2026-01-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0055_remove_lead_quotations_lead_quotation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_tax_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
